#!/usr/bin/env bash

function createOrg1() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/org1.raft/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/org1.raft/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:7254 --caname ca-org1 --tls.certfiles "${PWD}/organizations/fabric-ca/org1/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7254-ca-org1.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7254-ca-org1.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7254-ca-org1.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7254-ca-org1.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/org1.raft/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy org1's CA cert to org1's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/org1.raft/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/org1/ca-cert.pem" "${PWD}/organizations/peerOrganizations/org1.raft/msp/tlscacerts/ca.crt"

  # Copy org1's CA cert to org1's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/org1.raft/tlsca"
  cp "${PWD}/organizations/fabric-ca/org1/ca-cert.pem" "${PWD}/organizations/peerOrganizations/org1.raft/tlsca/tlsca.org1.raft-cert.pem"

  # Copy org1's CA cert to org1's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/org1.raft/ca"
  cp "${PWD}/organizations/fabric-ca/org1/ca-cert.pem" "${PWD}/organizations/peerOrganizations/org1.raft/ca/ca.org1.raft-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-org1 --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/org1/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-org1 --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/org1/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-org1 --id.name org1admin --id.secret org1adminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/org1/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7254 --caname ca-org1 -M "${PWD}/organizations/peerOrganizations/org1.raft/peers/peer0.org1.raft/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/org1/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/org1.raft/msp/config.yaml" "${PWD}/organizations/peerOrganizations/org1.raft/peers/peer0.org1.raft/msp/config.yaml"

  infoln "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7254 --caname ca-org1 -M "${PWD}/organizations/peerOrganizations/org1.raft/peers/peer0.org1.raft/tls" --enrollment.profile tls --csr.hosts peer0.org1.raft --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/org1/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/org1.raft/peers/peer0.org1.raft/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/org1.raft/peers/peer0.org1.raft/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/org1.raft/peers/peer0.org1.raft/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/org1.raft/peers/peer0.org1.raft/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/org1.raft/peers/peer0.org1.raft/tls/keystore/"* "${PWD}/organizations/peerOrganizations/org1.raft/peers/peer0.org1.raft/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:7254 --caname ca-org1 -M "${PWD}/organizations/peerOrganizations/org1.raft/users/User1@org1.raft/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/org1/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/org1.raft/msp/config.yaml" "${PWD}/organizations/peerOrganizations/org1.raft/users/User1@org1.raft/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://org1admin:org1adminpw@localhost:7254 --caname ca-org1 -M "${PWD}/organizations/peerOrganizations/org1.raft/users/Admin@org1.raft/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/org1/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/org1.raft/msp/config.yaml" "${PWD}/organizations/peerOrganizations/org1.raft/users/Admin@org1.raft/msp/config.yaml"
}

function createOrg2() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/org2.raft/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/org2.raft/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:8254 --caname ca-org2 --tls.certfiles "${PWD}/organizations/fabric-ca/org2/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-8254-ca-org2.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-8254-ca-org2.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-8254-ca-org2.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-8254-ca-org2.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/org2.raft/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy org2's CA cert to org2's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/org2.raft/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/org2/ca-cert.pem" "${PWD}/organizations/peerOrganizations/org2.raft/msp/tlscacerts/ca.crt"

  # Copy org2's CA cert to org2's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/org2.raft/tlsca"
  cp "${PWD}/organizations/fabric-ca/org2/ca-cert.pem" "${PWD}/organizations/peerOrganizations/org2.raft/tlsca/tlsca.org2.raft-cert.pem"

  # Copy org2's CA cert to org2's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/org2.raft/ca"
  cp "${PWD}/organizations/fabric-ca/org2/ca-cert.pem" "${PWD}/organizations/peerOrganizations/org2.raft/ca/ca.org2.raft-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-org2 --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/org2/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-org2 --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/org2/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-org2 --id.name org2admin --id.secret org2adminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/org2/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8254 --caname ca-org2 -M "${PWD}/organizations/peerOrganizations/org2.raft/peers/peer0.org2.raft/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/org2/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/org2.raft/msp/config.yaml" "${PWD}/organizations/peerOrganizations/org2.raft/peers/peer0.org2.raft/msp/config.yaml"

  infoln "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8254 --caname ca-org2 -M "${PWD}/organizations/peerOrganizations/org2.raft/peers/peer0.org2.raft/tls" --enrollment.profile tls --csr.hosts peer0.org2.raft --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/org2/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/org2.raft/peers/peer0.org2.raft/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/org2.raft/peers/peer0.org2.raft/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/org2.raft/peers/peer0.org2.raft/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/org2.raft/peers/peer0.org2.raft/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/org2.raft/peers/peer0.org2.raft/tls/keystore/"* "${PWD}/organizations/peerOrganizations/org2.raft/peers/peer0.org2.raft/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:8254 --caname ca-org2 -M "${PWD}/organizations/peerOrganizations/org2.raft/users/User1@org2.raft/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/org2/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/org2.raft/msp/config.yaml" "${PWD}/organizations/peerOrganizations/org2.raft/users/User1@org2.raft/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://org2admin:org2adminpw@localhost:8254 --caname ca-org2 -M "${PWD}/organizations/peerOrganizations/org2.raft/users/Admin@org2.raft/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/org2/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/org2.raft/msp/config.yaml" "${PWD}/organizations/peerOrganizations/org2.raft/users/Admin@org2.raft/msp/config.yaml"
}

function createOrderer() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/ordererOrganizations/raft

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/ordererOrganizations/raft

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:9254 --caname ca-orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-9254-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-9254-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-9254-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-9254-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/ordererOrganizations/raft/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/raft/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/raft/msp/tlscacerts/tlsca.raft-cert.pem"

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/ordererOrganizations/raft/tlsca"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/raft/tlsca/tlsca.raft-cert.pem"

# Loop through each orderer (orderer, orderer2, orderer3, orderer4) to register and generate artifacts
  for ORDERER in orderer orderer2 orderer3 orderer4; do
    if [ "${ORDERER}" = "orderer" ]; then
      HOST_DOMAIN="orderer.raft"
    else
      HOST_DOMAIN="${ORDERER}.raft"
    fi

    infoln "Registering ${ORDERER}"
    set -x
    fabric-ca-client register --caname ca-orderer --id.name ${ORDERER} --id.secret ${ORDERER}pw --id.type orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
    { set +x; } 2>/dev/null

    infoln "Generating the ${ORDERER} MSP"
    set -x
    fabric-ca-client enroll -u https://${ORDERER}:${ORDERER}pw@localhost:9254 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/raft/orderers/${HOST_DOMAIN}/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
    { set +x; } 2>/dev/null

    cp "${PWD}/organizations/ordererOrganizations/raft/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/raft/orderers/${HOST_DOMAIN}/msp/config.yaml"

    # Workaround: Rename the signcert file to ensure consistency with Cryptogen generated artifacts
    mv "${PWD}/organizations/ordererOrganizations/raft/orderers/${HOST_DOMAIN}/msp/signcerts/cert.pem" "${PWD}/organizations/ordererOrganizations/raft/orderers/${HOST_DOMAIN}/msp/signcerts/${HOST_DOMAIN}-cert.pem"

    infoln "Generating the ${ORDERER} TLS certificates, use --csr.hosts to specify Subject Alternative Names"
    set -x
    fabric-ca-client enroll -u https://${ORDERER}:${ORDERER}pw@localhost:9254 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/raft/orderers/${HOST_DOMAIN}/tls" --enrollment.profile tls --csr.hosts ${HOST_DOMAIN} --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
    { set +x; } 2>/dev/null

    # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
    cp "${PWD}/organizations/ordererOrganizations/raft/orderers/${HOST_DOMAIN}/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/raft/orderers/${HOST_DOMAIN}/tls/ca.crt"
    cp "${PWD}/organizations/ordererOrganizations/raft/orderers/${HOST_DOMAIN}/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/raft/orderers/${HOST_DOMAIN}/tls/server.crt"
    cp "${PWD}/organizations/ordererOrganizations/raft/orderers/${HOST_DOMAIN}/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/raft/orderers/${HOST_DOMAIN}/tls/server.key"

    # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
    mkdir -p "${PWD}/organizations/ordererOrganizations/raft/orderers/${HOST_DOMAIN}/msp/tlscacerts"
    cp "${PWD}/organizations/ordererOrganizations/raft/orderers/${HOST_DOMAIN}/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/raft/orderers/${HOST_DOMAIN}/msp/tlscacerts/tlsca.raft-cert.pem"
  done

  # Register and generate artifacts for the orderer admin
  infoln "Registering the orderer admin"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the admin msp"
  set -x
  fabric-ca-client enroll -u https://ordererAdmin:ordererAdminpw@localhost:9254 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/raft/users/Admin@raft/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/raft/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/raft/users/Admin@raft/msp/config.yaml"
}

