# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#


services:
  peer0.org1.smartbft:
    volumes:
      - ./podman/peercfg:/etc/hyperledger/peercfg

  peer0.org2.smartbft:
    volumes:
      - ./podman/peercfg:/etc/hyperledger/peercfg


