name: Fabric-Raft-Eval
version: '3.0'
client:
  credentialStore:
    path: ./wallet
    cryptoStore:
      path: ./wallet
  organization: Org1
  connection:
    timeout:
      peer:
        endorser: '300'
channels:
  reportchannel:
    created: true
    orderers:
      - orderer.example.com
    peers:
      peer0.org1.example.com:
        chaincodes:
          - id: report
            version: '1.0'
            language: golang
      peer1.org1.example.com:
        chaincodes:
          - id: report
            version: '1.0'
            language: golang
      peer0.org2.example.com:
        chaincodes:
          - id: report
            version: '1.0'
            language: golang
organizations:
  Org1:
    mspid: Org1MSP
    peers:
      - peer0.org1.example.com
      - peer1.org1.example.com
    adminPrivateKey:
      path: ../network/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/key.pem
    signedCert:
      path: ../network/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcerts/cert.pem
  Org2:
    mspid: Org2MSP
    peers:
      - peer0.org2.example.com
orderers:
  orderer.example.com:
    url: grpcs://localhost:7050
    grpcOptions:
      ssl-target-name-override: orderer.example.com
    tlsCACerts:
      path: ../network/crypto/ordererOrganizations/example.com/orderers/orderer.example.com/tls/ca.crt
peers:
  peer0.org1.example.com:
    url: grpcs://localhost:7051
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
    tlsCACerts:
      path: ../network/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
  peer1.org1.example.com:
    url: grpcs://localhost:8051
    grpcOptions:
      ssl-target-name-override: peer1.org1.example.com
    tlsCACerts:
      path: ../network/crypto/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/tls/ca.crt
  peer0.org2.example.com:
    url: grpcs://localhost:9051
    grpcOptions:
      ssl-target-name-override: peer0.org2.example.com
    tlsCACerts:
      path: ../network/crypto/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/ca.crt
certificateAuthorities: {}
