
volumes:
  orderer.smartbft:
  orderer2.smartbft:
  orderer3.smartbft:
  orderer4.smartbft:
  peer0.org1.smartbft:
  peer0.org2.smartbft:

networks:
  test:
    name: smartbft_net

services:

  orderer.smartbft:
    container_name: orderer.smartbft
    hostname: orderer.smartbft
    image: hyperledger/fabric-orderer:latest
    labels:
      service: hyperledger-fabric
      raft-network: smartbft
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=8055
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:8053
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer.smartbft:9543
      - ORDERER_METRICS_PROVIDER=prometheus
    working_dir: /root
    command: orderer
    volumes:
      - ../organizations-variant/ordererOrganizations/smartbft/orderers/orderer.smartbft/msp:/var/hyperledger/orderer/msp
      - ../organizations-variant/ordererOrganizations/smartbft/orderers/orderer.smartbft/tls/:/var/hyperledger/orderer/tls
      - orderer.smartbft:/var/hyperledger/production/orderer
    ports:
      - 8255:8055
      - 8253:8053
      - 9743:9543
    networks:
      - test

  orderer2.smartbft:
    container_name: orderer2.smartbft
    hostname: orderer2.smartbft
    image: hyperledger/fabric-orderer:latest
    labels:
      service: hyperledger-fabric
      raft-network: smartbft
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=8052
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:9055
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer2.smartbft:9546
      - ORDERER_METRICS_PROVIDER=prometheus
    working_dir: /root
    command: orderer
    volumes:
      - ../organizations-variant/ordererOrganizations/smartbft/orderers/orderer2.smartbft/msp:/var/hyperledger/orderer/msp
      - ../organizations-variant/ordererOrganizations/smartbft/orderers/orderer2.smartbft/tls/:/var/hyperledger/orderer/tls
      - orderer2.smartbft:/var/hyperledger/production/orderer
    ports:
      - 8252:8052
      - 9255:9055
      - 9746:9546
    networks:
      - test

  orderer3.smartbft:
    container_name: orderer3.smartbft
    hostname: orderer3.smartbft
    image: hyperledger/fabric-orderer:latest
    labels:
      service: hyperledger-fabric
      raft-network: smartbft
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=8056
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:9057
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer3.smartbft:9547
      - ORDERER_METRICS_PROVIDER=prometheus
    working_dir: /root
    command: orderer
    volumes:
      - ../organizations-variant/ordererOrganizations/smartbft/orderers/orderer3.smartbft/msp:/var/hyperledger/orderer/msp
      - ../organizations-variant/ordererOrganizations/smartbft/orderers/orderer3.smartbft/tls/:/var/hyperledger/orderer/tls
      - orderer3.smartbft:/var/hyperledger/production/orderer
    ports:
      - 8256:8056
      - 9257:9057
      - 9747:9547
    networks:
      - test

  orderer4.smartbft:
    container_name: orderer4.smartbft
    hostname: orderer4.smartbft
    image: hyperledger/fabric-orderer:latest
    labels:
      service: hyperledger-fabric
      raft-network: smartbft
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=8058
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:9059
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer4.smartbft:9548
      - ORDERER_METRICS_PROVIDER=prometheus
    working_dir: /root
    command: orderer
    volumes:
      - ../organizations-variant/ordererOrganizations/smartbft/orderers/orderer4.smartbft/msp:/var/hyperledger/orderer/msp
      - ../organizations-variant/ordererOrganizations/smartbft/orderers/orderer4.smartbft/tls/:/var/hyperledger/orderer/tls
      - orderer4.smartbft:/var/hyperledger/production/orderer
    ports:
      - 8258:8058
      - 9259:9059
      - 9748:9548
    networks:
      - test




  peer0.org1.smartbft:
    container_name: peer0.org1.smartbft
    hostname: peer0.org1.smartbft
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
      raft-network: smartbft
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.org1.smartbft
      - CORE_PEER_ADDRESS=peer0.org1.smartbft:7153
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7153
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.smartbft:7152
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7152
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.smartbft:7153
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.smartbft:7153
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer0.org1.smartbft:9544
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0org1"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
      - ../organizations-variant/peerOrganizations/org1.smartbft/peers/peer0.org1.smartbft:/etc/hyperledger/fabric
      - peer0.org1.smartbft:/var/hyperledger/production
    working_dir: /root
    command: peer node start
    ports:
      - 7353:7153
      - 9744:9544
    networks:
      - test

  peer0.org2.smartbft:
    container_name: peer0.org2.smartbft
    hostname: peer0.org2.smartbft
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
      raft-network: smartbft
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.org2.smartbft
      - CORE_PEER_ADDRESS=peer0.org2.smartbft:9153
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9153
      - CORE_PEER_CHAINCODEADDRESS=peer0.org2.smartbft:9152
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9152
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.smartbft:9153
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.smartbft:9153
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer0.org2.smartbft:9545
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0org2"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
      - ../organizations-variant/peerOrganizations/org2.smartbft/peers/peer0.org2.smartbft:/etc/hyperledger/fabric
      - peer0.org2.smartbft:/var/hyperledger/production
    working_dir: /root
    command: peer node start
    ports:
      - 9553:9153
      - 9745:9545
    networks:
      - test

